all:
	rst2html.py --stylesheet=orapig.css orapig.rst >orapig.html
	rst2html.py --stylesheet=orapig.css configomat.rst >configomat.html
	#rst2latex.py orapig.rst >orapig.latex
	#rst2latex.py configomat.rst >configomat.latex

clean:
	rm -f orapig.html configomat.html
	rm -f orapig.latex configomat.latex
